### ISSUE TITLE
3DMigoto is not injecting into Genshin Version 3.0

### ISSUE THREAD

**Issue by ClickClack7531** [SilentNightSound/GI-Model-Importer#33] opened 2022-08-27 02:57 UTC
For the past few days I've been trying to be 3Dmigoto to work with the new Genshin Impact update 3.0. When I open the 3DMigoto mod loader, it opens just fine, but after I open Genshin, the mod loader closes, but no green text overlay to be seen. My mods didn't load either. I made sure that I had set the correct director in the d3dx.ini file. I made sure that every time I entered my world, I pressed F10 to load the mods. I even changed my mod's folder names to the characters they were modding (Like "KeqingMod") but none worked.

So is this a problem on my side? Or is this an actual bug?

I noticed that someone asked this same question in the Issues tab, but his Issue was closed with no resolution nor explanation. Just pointing that out.

**Comment by SilentNightSound** [comment] 2022-08-27 16:17
I can confirm that 3DMigoto works with version 3.0 without any issues - version 3.0 did change a few things related to how models are represented in-game, but none of it has any impact on how the program loads or works (it only impacts modders who are making mods with 3.0 characters). In fact, unless Mihoyo makes significant changes 3DMigoto should continue to work with all versions of genshin by default.

The mod loader closing is expected - it should close after attempting to inject the program into the game. The names of the mod folders doesn't matter - they don't need to match the character.

In terms of troubleshooting, I can mostly just point to the ones mentioned in the [troubleshooting guide](https://github.com/SilentNightSound/GI-Model-Importer/blob/main/Guides/Troubleshooting.md#installation-issues ) since the vast majority of issues are one of those. The only other ones I have seen are incompatibility with other modding tools (akebi/reshade) or the path format being incorrect (e.g. using / instead of \\) - you can also just try using the string "target = GenshinImpact.exe" and it will try to find the correct process on its own (though this has some reliability issues over using the full path).

You can also try looking in the d3d11_log.txt to see if anything interesting is printed - I didn't write that portion of the code so I am less familiar with it, but if there was an error it should show up there.

For the other Issue, the person closed it themselves after a period of time - I don't know why (either they gave up or they were able to get it to work).

**Comment by ClickClack7531** [comment] 2022-08-27 23:41
> I can confirm that 3DMigoto works with version 3.0 without any issues - version 3.0 did change a few things related to how models are represented in-game, but none of it has any impact on how the program loads or works (it only impacts modders who are making mods with 3.0 characters). In fact, unless Mihoyo makes significant changes 3DMigoto should continue to work with all versions of genshin by default.
> 
> The mod loader closing is expected - it should close after attempting to inject the program into the game. The names of the mod folders doesn't matter - they don't need to match the character.
> 
> In terms of troubleshooting, I can mostly just point to the ones mentioned in the [troubleshooting guide](https://github.com/SilentNightSound/GI-Model-Importer/blob/main/Guides/Troubleshooting.md#installation-issues) since the vast majority of issues are one of those. The only other ones I have seen are incompatibility with other modding tools (akebi/reshade) or the path format being incorrect (e.g. using / instead of \) - you can also just try using the string "target = GenshinImpact.exe" and it will try to find the correct process on its own (though this has some reliability issues over using the full path).
> 
> You can also try looking in the d3d11_log.txt to see if anything interesting is printed - I didn't write that portion of the code so I am less familiar with it, but if there was an error it should show up there.
> 
> For the other Issue, the person closed it themselves after a period of time - I don't know why (either they gave up or they were able to get it to work).

Ohhhhh, that clears up alot, mb. Thanks for the help bro

**Comment by ClickClack7531** [comment] 2022-08-28 19:29
> I can confirm that 3DMigoto works with version 3.0 without any issues - version 3.0 did change a few things related to how models are represented in-game, but none of it has any impact on how the program loads or works (it only impacts modders who are making mods with 3.0 characters). In fact, unless Mihoyo makes significant changes 3DMigoto should continue to work with all versions of genshin by default.
> 
> The mod loader closing is expected - it should close after attempting to inject the program into the game. The names of the mod folders doesn't matter - they don't need to match the character.
> 
> In terms of troubleshooting, I can mostly just point to the ones mentioned in the [troubleshooting guide](https://github.com/SilentNightSound/GI-Model-Importer/blob/main/Guides/Troubleshooting.md#installation-issues) since the vast majority of issues are one of those. The only other ones I have seen are incompatibility with other modding tools (akebi/reshade) or the path format being incorrect (e.g. using / instead of \) - you can also just try using the string "target = GenshinImpact.exe" and it will try to find the correct process on its own (though this has some reliability issues over using the full path).
> 
> You can also try looking in the d3d11_log.txt to see if anything interesting is printed - I didn't write that portion of the code so I am less familiar with it, but if there was an error it should show up there.
> 
> For the other Issue, the person closed it themselves after a period of time - I don't know why (either they gave up or they were able to get it to work).

Hm. Are you sure GIMI works on Genshin version 3.0? Because I am still having issues. The trouble shooting I tried are 1. Completely deleting the version of GIMI 3Dmigoto I have along with the mods I want to use, redownloading the latest version of GIMI and the said mods and injecting the newly downloaded mods with the newly downloaded 3DMigoto into Genshin without changing anything (I didnt need to change the d3dx.ini file because my Genshin files were in the default folder) and it didnt work. I tried running GIMI alone, without any other software (Like Cultivation). Didnt work either, I tried using around 20 - 30 mods and none of them worked. And every time I tried using 3DMigoto, there was no green text overlay.

I am beyond confused and I have no idea what's causing this. The mods I used are working, because I've tested them out myself before 3DMigoto decided to just stop working, so I know it's not them. I know it's not Genshin Inpact either because I repaired the game, multiples times, and tried using other modding software, and they work just fine. Do you have any idea what could be causing this? Because I am clueless.

**Comment by SilentNightSound** [comment] 2022-08-28 20:05
Yes, I can confirm for sure that GIMI works on version 3.0 - I tested using the 2.8.5 beta, 3.0 on private servers and 3.0 on official servers as well and all three were able to load with no issues. I've also confirmed with other people that are able to load the program. 

One method you can use is to try the "for development" version instead of the for playing version - the development version has the green text on the top and bottom so you can tell right away if the program is loading properly when it boots up, while the for playing version does not.

After that, double check the path again - you mentioned it is the default, but it is possible that it is on another drive or something which might be causing issues. Also, can use "target = GenshinImpact.exe" to try to inject into the process as well. And while it might be an obvious check, make sure everything has been extracted from the zip file.

tbh, other than that I have no idea what could be causing the issue. GIMI works pretty much out of the box in 99% of cases - I've only come across 2 or 3 where the issue wasn't some sort of misconfiguration, and those were as a result of incompatibility with reshade/akebi/etc. or on the Chinese version due to non-ascii characters in the path. Sometimes it fails to inject randomly, but it usually only happens once or twice occasionally and not consistently many times in a row.

**Comment by SilentNightSound** [comment] 2022-08-28 20:44
Oh, also one more thing to note - even if the Genshin program or private server is damaged (wrong resources/mismatched grasscutter/not connecting to server/etc.), GIMI should still inject and run properly so generally you don't need to troubleshoot the game itself, just GIMI.

**Comment by ClickClack7531** [comment] 2022-08-29 02:55
> Oh, also one more thing to note - even if the Genshin program or private server is damaged (wrong resources/mismatched grasscutter/not connecting to server/etc.), GIMI should still inject and run properly as long as the game can start.

Hey. I was able to fix the problem, and it was all thanks to your help! Thanks btw. But yeah, you were correct. It was because I was using the regular GIMI. I never knew the green text was unique to the developer version of GIMI. It seems to be that the regular version is bugged or unsupported on my computer for some reason, because all I did was switch the files and all my mods were working again.

**Comment by ClickClack7531** [comment] 2022-08-29 02:59
> Oh, also one more thing to note - even if the Genshin program or private server is damaged (wrong resources/mismatched grasscutter/not connecting to server/etc.), GIMI should still inject and run properly as long as the game can start.

Sorry if I seemed pretty annoyed. I hate when things break for no reason, it really gets on my nerves.

**Comment by SilentNightSound** [comment] 2022-08-29 04:45
Glad to hear the issue was resolved! I'll take a look at why the for playing version has issues, though the two versions are basically identical apart from a single line in the .ini which turns off the green text/buffer hunting - I don't _think_ it should cause anything to break, but I'll double check.

**Closed by SilentNightSound** 2022-08-29 04:45 UTC

**Comment by MaskaSpektra** [comment] 2023-07-25 15:15
Фs I understand now this application does not work? I tried to log in, but it says that I play unofficial genshinю
