### ISSUE TITLE
Import ib\buf modded model files into Blender?

### ISSUE THREAD

**Issue by n1tr0ms** [SilentNightSound/GI-Model-Importer#76] opened 2023-03-26 09:26 UTC
Want to import a custom model into blender but the plugin for it doesn't support ib\buf files which is the only model files:
https://gamebanana.com/mods/431152

TravelerGirl.ini contans the data for ib\buf files and other additional files (textures in dds for example), but the blender plugin doesn't support such import - only vb.txt\ib.txt, vb\ib, vgmap, txt.

**Comment by SilentNightSound** [comment] 2023-03-26 17:15
Hello. The program does not support loading created mods back from the mod folders into Blender

**Comment by Wasmachineman-NL** [comment] 2023-05-21 13:07
Damn, I would have loved to port the Female Albedo to VRChat but I guess that won't be happening any time soon :(

**Comment by RrdUI** [comment] 2023-07-11 17:26
@SilentNightSound 
Hello. Are you planning to add support for importing/exporting ib\buf files to the addon?

**Comment by ulvhaka** [comment] 2023-07-26 17:17
I found this (http://modderbase.com/printthread.php?tid=766 )
''g1m_import: this tool allows to perform the opposite operatin to above, import .vb/.ib files into .g1m files. ''

**Comment by leotorrez** [comment] 2023-09-01 20:59
Reversing mods into blender projects in this manner is heavily discouraged cause it could entail stealing the hard work of the modding community. Instead we recommend asking the mod maker to share their blend files instead. Most are willing to help you on your projects, just reach out to them

**Comment by aethrith** [comment] 2023-10-01 01:28
@ulvhaka Very late but how do you use g1m_import? When I open it I just get a bad usage error, and the usage instructions are very confusing to me :(

**Comment by EthanLee03** [comment] 2023-10-01 07:48
Im looking for the same thing mod creator quit and I want to modify it, hopefully someone knows how

**Comment by SilentNightSound** [comment] 2023-10-01 23:29
Hello. As Leo mentioned earlier, we have decided to not include this functionality in the plugin or release code that allows reversal of mods into Blender (there has already been at least 1 major incident caused by it). There are no plans to add this functionality in the future, so I will close this issue.

**Closed by SilentNightSound** 2023-10-01 23:29 UTC

**Comment by nightboysfm** [comment] 2024-12-25 23:20
it seems a bit wrong to act as a moralizer and say you have to respect the rules when you're cheating yourself by stealing hoyoverse's work and not respecting their rules
things should apply both ways, and not just when it's in someone's personal interest (often greedy modders that lock stuff behind a paywall).
aren't we part of the sharing philosophy?
best regards

**Comment by leotorrez** [comment] 2024-12-27 07:20
> It seems a bit wrong to act as a moralizer and say you have to respect the rules when you're cheating yourself by stealing hoyoverse's work and not respecting their rules. This is even worse when some people are making money of it... Things should apply both ways, and not just when it's in someone's personal interest (often greedy modders that lock stuff behind a paywall). Aren't we part of the sharing philosophy? Best regards

The code for it is public in several repositories. If someone needs it they can find it with some googling. We chose not to include it in our tools to avoid conflicts within the community. Is not a matter of morale, right/wrong or rules. We are simply developing a plugin and we chose to support or not some functionalities. Please don't try to force us to work on things we don't want to.

As for paywalled content here you have some recommendations on the subject: [https://leotorrez.github.io/modding/guides/getting-mods#paid-content-and-piracy](https://leotorrez.github.io/modding/guides/getting-mods#paid-content-and-piracy)

**Comment by 4Brad-23** [comment] 2025-06-26 06:58
There are other ways of ripping these models, so don't flatter yourself, it just takes time, and we were calling for an easier way.
